### ISSUE TITLE
Release 1.343.20190926 - Issue regarding bookmarks and scan results!

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#100]
This is a bug in the Mac 1.343.20190926 release(idk about the others)
*Verified that rolling back to Mac 1.342.20190915 release seems to fix the problem.

So when I first open the app, I click on the Favorites pop window to scan for new replays and once it finishes, I scroll through and view/watch what I want. After I am done, like always, I exit out of the favorites pop window, then I click on it again to re-scan for any new replays that might of happen while I was on but I noticed that the same accounts seems to reappear. The replays of those accounts that I have just watched has the green eyeball next to them, so that part works fine, but for some reason the scanning doesn't register that those accounts have already been scanned. I tried a number of times and also closed the app and opened it, but still no luck. Rolled back to earlier release and everything is back to normal.
If I see anything else I will post. Thanks again

**Comment by thecoder75** [comment]
I'm noticing this error too now and all testing is showing its working but not working.

**Comment by ReinerNJ61** [comment]
I'm noticing similar issues, I have 177 followings, I unfollow 20 and refresh and it shows 157, all good, I close and reopen LMPT, go into bookmarks and I have 177 again.  For some reason, changes aren't being saved.  I have reverted to previous version now and it works fine.  I'm on windows 10 x64

**Comment by thecoder75** [comment]
For some reason the scan results are not being saved even though the call to save them is being done.  This error only recently appeared and is being investigated heavily by me.  I'm not sure at this time when I'll issue a new release but it won't be until this issue is resolved 100%.

**Comment by thecoder75** [comment]
This issue has been resolved.
