### ISSUE TITLE
[RESOLVED] comments timestamp bug

### ISSUE THREAD

**Issue by rastafaa** [thecoder75/liveme-pro-tools#103]
The timestamps on downloaded comments are broken after the time goes over an hour. It'll go from 59:59 to 1:61:00, for example. The minutes portion doesn't get reset to 00 after the hour.

Minor bug but it messes with subtitle creation.

**Comment by thecoder75** [comment]
I will look into this and see about getting it fixed before the next release is built.

**Comment by thecoder75** [comment]
This issue should be resolved now.
