### ISSUE TITLE
[BUG] Copy Replay URL list to clipboard doesn't work properly?

### ISSUE THREAD

**Issue by tp9ine** [thecoder75/liveme-pro-tools#106]
I have tried it a couple of times and it either doesn't copy the full list (only copied about 60 out of 150+ replays available) or it copied them in some sort of garbled order, and I pasted them in notepad and it created several dozen blank lines.

**Comment by thecoder75** [comment]
I've been able to reproduce this issue myself and will begin investigating it more to as why its happening.

Not sure when a fix will be released.

**Comment by thecoder75** [comment]
I've updated the code base to use the properVideoSource call to help fix this.  However in light of the new LiveMe API changes, this feature may or may not continue to work now.
