### ISSUE TITLE
File name variables not showing / issue with special characters

### ISSUE THREAD

**Issue by happykeppi** [thecoder75/liveme-pro-tools#11]
The available variables for the file name (like %%broadcaster%%) are currently not showing up in the settings. A download also crashes if the username or video title contains any kind of special characters:

> A Javascript error occured in the main process
> Uncaught Exception:
> Error: ENOENT: no such file or directory, open
> 'path/filename'

Maybe it's possible to automatically replace all problematic character (< * > etc.) with a neutral ones.

**Comment by thecoder75** [comment]
Under the Filename Template field in settings is a list of all of the supported variables for download filenames.

![screenshot at 2018-03-02 07 22 38](https://user-images.githubusercontent.com/30754178/36898842-896e0732-1dea-11e8-9623-fd0a8bbca092.png)

I have added a filter to remove illegal characters now from the filenames to help fix the crash.

**Comment by happykeppi** [comment]
Yes, I know. I eventually saw the variables in the source code. However, this is what it looks like to me within the program:

![1](https://user-images.githubusercontent.com/13066275/36899054-b81cd44a-1e1d-11e8-867c-c1e7a6fd4ba9.jpg)

Does the installed Java version (8 update 161) matter in any way?

**Comment by thecoder75** [comment]
No, LiveMe Pro Tools does not use Java.  Why its not showing on the Windows version is a mystery to me as it should be present like the screenshot I show.

I will try and get a test Windows 10 going today so I can review the issue more closely.

**Comment by happykeppi** [comment]
Alright. I am running the tool on Windows 8.1 Pro 64bit by the way. Let me know if I can be of any help.

**Comment by happykeppi** [comment]
Brief feedback; the file name variables started showing up with version 1.81.20180302, but later disappeared again with the current 1.90.20180302 release. The downloads are still crashing with certain characters in the file name including * (asterisk) or symbols like a heart.

**Comment by thecoder75** [comment]
The variables table was accidentally getting wiped out by the home function.  It has been fixed along with the illegal characters in filename issue in the 1.92.20180305 release.
