### ISSUE TITLE
[Question] Setting up external players on windows?

### ISSUE THREAD

**Issue by uristmcf** [thecoder75/liveme-pro-tools#112]
I feel like an idiot, but I'll ask. How do I set up MPC-HC to play the files on windows? My current install is at C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe and if I link to it and do %url%, it doesn't work. I tried linking to just the folder and doing %url% and that didn't work either. Not really sure how to set this up.

**Comment by starsaillor** [comment]
I'm having the same problem, I can't seem to figure out how to set up the ext player.

**Comment by tatterz91** [comment]
Yeah I'm confused what to do!

**Comment by thecoder75** [comment]
See #110 for details

**Comment by cmkeeper9** [comment]
@tatterz91 can you post what you entered for MPC-HC windows values?  Would be very helpful for non coders.

**Comment by starsaillor** [comment]
U gotta put " before and after the path
