### ISSUE TITLE
[Question] What media player was the internal one designed like?

### ISSUE THREAD

**Issue by lifesuckz69** [thecoder75/liveme-pro-tools#113]
Was the internal one based on anything? 
I don't want to use VLC cause I use that for other stuff, so I don't want to mess up my settings and MPV I can't even find an option menu.

What I need is a player that has forward-backward 1 frame with arrows, rotate, mute across several instances and opens in the same window and keeps size of the last window.

Oh yeah, talking about windows

> 
> 
> I've always used MPC-HC.. works perfectly and can add subtitles so it'll show the comments similar to the internal player that I rarely used. Also has the benefit of opening multiple streams at once.

Thanks, that one does exactly what I want.

**Comment by thecoder75** [comment]
The internal player was based on multiple players, so unfortunately there is no one solution.  [MPV](https://mpv.io) so far has been one of the smoothest players available and allows frame stepping using arrow keys along with time stepping using the mouse wheel.  

The two that are recommended the most have been referred to and setup instructions provided in #110.

**Comment by lifesuckz69** [comment]
Thanks, but my issue with mbv is that I don't even find settings.
I need it to open in the same instance and retain size between each open. Right now it opens a new window each time and doesn't keep it in the same place and size as the last one.
I know how to setup VLC like that, but as mentioned I don't want to have to change it every time I used it for something else in between.

**Comment by rastafaa** [comment]
I've always used MPC-HC.. works perfectly and can add subtitles so it'll show the comments similar to the internal player that I rarely used. Also has the benefit of opening multiple streams at once.
