### ISSUE TITLE
[REQUEST] Filter Search Results ?

### ISSUE THREAD

**Issue by toendeaf** [thecoder75/liveme-pro-tools#114]
Is there any possibility of introducing this for the search results please ?

1.Filter by country
2. Filter to only show users with replays 

Thank you

**Comment by thecoder75** [comment]
1 is more possible than 2.  Due to the fact that a lot of calls have to be made to the server to verify there are no replays, adding option 2 could cause people to get blocked by the servers for excessive usage.

**Comment by toendeaf** [comment]
Thank for the reply Coder. I guess the issue now is that LM has removed about 95% of content, so whenever you do a search by username, 95% of them have zero replays and are therefore (to me anyway) of no value.would it be possible to do something like return all results but then allow the user to show only those with replays, in other words filter on the subset of returned values ?

Thank you for whatever you can do !

**Comment by thecoder75** [comment]
See #115 for details on the *Filter by Country* option status.

No 2 requires a lot of coding to be changed to support it due to how data is loaded and handled and may take some time.

**Comment by toendeaf** [comment]
Beautiful work, this can be set to completed now Coder.Thank you
