### ISSUE TITLE
[QUESTION] Exclude Countries in settings

### ISSUE THREAD

**Issue by toendeaf** [thecoder75/liveme-pro-tools#115]
Where does this actually exclude the countries, as if I select to exclude all except one country, I still see all countries in search results, all countries in follows/followings (although you can then filter this by country), so jjust wondering where this function actually takes effect ?

Thank you Coder

**Comment by thecoder75** [comment]
I will look into this and see what is going on as it was a feature added a long time ago by another contributor.

**Comment by toendeaf** [comment]
Thanks Coder

**Comment by thecoder75** [comment]
Originally this option **ONLY** applied to the fans and followings window, no other spot in the app.

I've added it to the Username search results as well.

**Comment by toendeaf** [comment]
Thanks Coder - can't wait for new release now :-)
