### ISSUE TITLE
My Verification that the internal video player in release 1.350.20191014(macos) works.

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#116]
Hey Coder, just wanted to update you and all the people who use LMPT on this...
Shout out to ZZxxqq on gitter for also verifying this. 
So, I have been using VLC for my external video player, and yes it does work, but it is not as fluid as the internal video player. It's slower, frames seem to skip sometimes, and just a few extra clicks I have to do to watch replays (I'm using MacOs, idk about the VLC windows app). That said it does work which is the most important thing. I know LiveMe has updated some things on there end which caused some problems with the internal player, so I took a chance and decide to reinstall the 1.350.20191014 release just to see if the internal player is back to working and I can 100% Verify that it does work. I have been using it for about an hour now and all the replays play fine. I am going to continue to keep using the app for the next few hours just to make sure and I will post it the update here. Happy Thanksgiving to everyone =)

**Comment by stingersplash** [comment]
Ok so I tested it for a few more hours and everything works just fine. Seems like Liveme was just updating there servers, maybe? I will be sticking with release 1.350.20191014 as I prefer the fluidity of the internal player. Everyone have a safe and happy holidays.

**Comment by thecoder75** [comment]
The internal video player is returning in the next release.
