### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by prince911** [thecoder75/liveme-pro-tools#12]
You could add
Minimize button
Feature
Show accounts no replay 

and Thank you

**Comment by thecoder75** [comment]
Minimize button I see no problem adding.  You can control the `Show Accounts with no Replays` in Settings already.  

As far as Feature, not sure what you mean here.

**Comment by prince911** [comment]
i have 3352 folowing jast show 1939 
ineed to remove 1413 Reason
no Replays

**Comment by thecoder75** [comment]
Gotcha.

I've already been working on adding a cleanup function for both the Bookmarks and the Profile History to clean them up based on choices of certain criteria.

**Comment by thecoder75** [comment]
Also, the Minimize button has been added to all windows except the player.

**Comment by happykeppi** [comment]
Would it be also possible to add a 'X' / cancel button for the download queue? It's super annoying if the download fails (due to special characters for example) and the program keeps trying to perform the download again and again.

**Comment by prince911** [comment]
liveme-pro-tools-setup-1.90.20180302.exe.blockmap

wait is blockmap wait he can do ??

**Comment by thecoder75** [comment]
The blockmap files are generated by the automated build system and are not needed.

**Comment by thecoder75** [comment]
See latest build for results.
