### ISSUE TITLE
[Request] Pop Out from search results

### ISSUE THREAD

**Issue by toendeaf** [thecoder75/liveme-pro-tools#120]
So the search now works beautifully, however, say you search for specific name, and it gives you say 30 hits, if you choose one, it open this in the same window, so you have to re-run the search for the next one. Same thing happens if you go back to change a setting - opens in same window, so you have to run the search again.
Solution is once you select an item from search, it opens in a new window, that way you can revert to search results when finished. Not sure how you can fix the settings similar issue, unless there is a Go Back option, which just reverts you to the previous page. This might also work for the search, but I think separate window defo works best for this one.

**Comment by thecoder75** [comment]
See [here](https://github.com/Lewdninja/liveme-pro-tools-vue) for a version being maintained with this feature.
