### ISSUE TITLE
[Question] List of Following/Followers/Replays Issue Possibly

### ISSUE THREAD

**Issue by lifesuckz69** [thecoder75/liveme-pro-tools#121]
I also write in the gitter, but I feel that this needs a proper issue thread:

At first the new version worked, but suddenly it had a database error and everything took forever.
Then I realized I don't see some of my bookmarks, even though I removed all the filters in the options.
Then it suddenly stopped showing ANYTHING in the bookmarks list, except the bookmarks (with this I mean if I hit Followers, it didn't show any) until I hit reset everything, which fixed that issue, but did NOT reset everything and the initial issue still remained.
I then went into the files and deleted everything except the bookmarks, so basically reset it myself.

Now it works, but still does not show all the bookmarks (113 of 113 scanned, 82 shown) and even the accounts with replays shows as 0 replays, but when I click on them, they are there.

**EDIT: Ok, so after clicking "Show all bookmarks" in the bookmark list and switching to "active last xx days" and then back to all, it now shows the correct Replay amount.
Still have the issue of it only showing 82 from 113 though, so that still remains**.

**Comment by lifesuckz69** [comment]
Ok, now another issue: After a while of using the program, the search breaks again and it shows: "Data error, resubmit search query again" and everything is super slow

**Comment by calluch** [comment]
I lost all my bookmarks....something happened with liveme....I am now sure what it was but I lost everything....4000 bookmarks

**Comment by thecoder75** [comment]
@lifesuckz69 Sounds like LiveMe is throttling your connections cause you are triggering too many API requests.  Also lately a lot of accounts are now getting banned for following other accounts that are getting banned.  THey're stopping people from tracking others for wins.

**Comment by thecoder75** [comment]
@callch Your issue is a separate issue and may have been caused by a corrupt data file causing everything to get wiped.

I test this app on a regular basis and note any issues that cause data loss or major network issues to ensure that they never get out into the general usage.  As always, it is highly recommended you back up your data at regular intervals (weekly/monthly) in case of issues or glitches that may cause loss of data.

**Comment by lifesuckz69** [comment]
> 
> 
> @lifesuckz69 Sounds like LiveMe is throttling your connections cause you are triggering too many API requests. Also lately a lot of accounts are now getting banned for following other accounts that are getting banned. THey're stopping people from tracking others for wins.

The weird part about that is that i didn't have that issue before and first encountered it with the latest version. 
How can I figure out if I got banned for following other banned accounts? Any way to check that?

**Comment by thecoder75** [comment]
If all of your issues started Monday then don't worry about it as there was some LiveMe network issues on Monday that caused things to glitch.

**Comment by lifesuckz69** [comment]
> 
> 
> If all of your issues started Monday then don't worry about it as there was some LiveMe network issues on Monday that caused things to glitch.

Oh...well that might be a stupid coincidence then. It was indeed monday. Don't have time right now/today to check, but next time I will look out for the issues and report if they are still there or if that is resolved.

**Comment by lifesuckz69** [comment]
Ok, so the issue with the bookmarks not showing all is still there. 
For example: If I search for the name of the bookmarked person, under "username like" I can find him. I also have him favorited with the yellow star (though it's only yellow if I go to the replays, not on the search results) and that is one of the accounts I can't see in the bookmark list. It still says 114 of 114 bookmarks scanned, 82 shown. No filters or settings that would remove the account.

**Comment by thecoder75** [comment]
I've confirmed an issue regarding the bookmarks scanning and will investigate.  Not sure when a fix will be pushed out for it.

**Comment by thecoder75** [comment]
@lifesuckz69 The reason for saying only 82 shown is that 82 of the 114 accounts bookmarked actually had activity in the last 50 years.  Basically if nothing has changed on that account since you first bookmarked it, including no new replays, no changes in the fans or following counts, then its a stale account and is hidden.

I've fixed it now to truly be all accounts and will build an update when I have time.

**Comment by lifesuckz69** [comment]
> 
> 
> @lifesuckz69 The reason for saying only 82 shown is that 82 of the 114 accounts bookmarked actually had activity in the last 50 years. Basically if nothing has changed on that account since you first bookmarked it, including no new replays, no changes in the fans or following counts, then its a stale account and is hidden.
> 
> I've fixed it now to truly be all accounts and will build an update when I have time.

Sounds good and will try that update when it's out. Something to consider though: When I go to the recent activity button, the missing account (I assume it's not only that one, but that is the one I regularily check) sometimes has new followings, so there is activity.

**Comment by lifesuckz69** [comment]
I'm closing this as now it shows the full amount. Thanks for fixing.
