### ISSUE TITLE
how do i get my liveme id to listen for my liveme chat incoming messages?

### ISSUE THREAD

**Issue by L2L2L** [thecoder75/liveme-pro-tools#126]
I remember they use to show the liveme id on the screen when you stream, but they don't anymore, where else can i find my liveme id on the app so i can plug it into a function to listen to live chat message coming in from my livme stream.

**Comment by thecoder75** [comment]
When you view the Account Details you will see to the right of their Avatar what is called a Long ID and a Short ID.  The Short ID is what use to be on the videos.
