### ISSUE TITLE
how do i find my liveme id? And reading chat live from this api is possible??

### ISSUE THREAD

**Issue by L2L2L** [thecoder75/liveme-pro-tools#127]
my live id use to be on the stream when you stream on live, where can i find it now? and i can read my chat live with this api right?

**Comment by thecoder75** [comment]
See #126 for how to get your LiveMe IDs.  The API used in this project DOES NOT allow for real-time message viewing.  It is designed for accessing replays (previous live streams) only.

Please limit your questions to the usage and/or bug reporting for the LiveMe Pro Tools itself, not off-topic questions like this and the previous one asked.
