### ISSUE TITLE
Follow from Home window not working

### ISSUE THREAD

**Issue by ncarpenter** [thecoder75/liveme-pro-tools#133]
Not sure if this is just the Mac build but trying to follow a user from the home window after doing a search doesn't work. The button isn't clickable and I can't figure out why. No errors are thrown.

**Comment by thecoder75** [comment]
It's not a bug but just an indicator as to if you have them already bookmarked or not.

**Comment by ncarpenter** [comment]
Ah, thanks! That was breaking my head.

**Comment by thecoder75** [comment]
No problem.  Thank you btw for the recent commits.

**Comment by ncarpenter** [comment]
Np. Glad you're back working on the app!
