### ISSUE TITLE
General suggestions

### ISSUE THREAD

**Issue by Grindteeth** [thecoder75/liveme-pro-tools#14]
First of all, big thanks for this project, it's fun to watch how it develops and its core function (downloading) works pretty well!

I'm just a simple end user so I have no idea if my suggestions are hard to implement, but hopefully I give some ideas of possible improvements. I'll just list bugs I've come across and also suggestions of new features.

I'm on Windows 10. Note that I have not yet had the time to test the version from today (I'm still on 2 feb version).

Bugs:

* The "new broadcasts" feed does not work anymore (it's just empty)
* Concurrent download limit rarely works - all downloads start once added
* Some characters in title (like "?") are not downloadable - receives error.
* The syntax for filenames often disappears in the settings.

Suggestions:
* Limit the amount of retries - some files end up in a retry loop and will never finish.
* Ability to cancel active downloads (maybe by right clicking them?)
* Remove the long user ID unless it's used for something.
* Search and sort functions for the subscriptions. Sorting by "latest replay" would be sweet.
* Some graphical change to indicate which files have been added to the download queue (maybe change color to the download symbol? Or change symbol to a down arrow)
* Ability to "mark read" in the subscription list when filtered for new broadcasts.
* Ability to select file location for backup
* Ability to select file location of the database/subscription list. The system drive is not optimal.

Luxuary improvements:
* popup to indicate new live/video - maybe even with sound. Alternatively, just sound without popup
* Detachable download window
* video player remembering volume/mute settings
* LAMD integrated into main program

I could probably add more if you are interested. 
Best regards from a user

**Comment by thecoder75** [comment]
New replays now show on the home screen.  Concurrent download issue has been resolved.  Illegal characters in the filename issue has been fixed.  The issue of the syntax/variables has been resolved as well.

**Comment by Grindteeth** [comment]
Thanks, you work quickly :) I will try it out tonight. I'll close this issue for now.
