### ISSUE TITLE
1.92.20180305 release is crashing on startup (Win7)

### ISSUE THREAD

**Issue by happykeppi** [thecoder75/liveme-pro-tools#15]
(OS: Windows 7 64bit)

![1](https://user-images.githubusercontent.com/13066275/36995667-f3ee22b4-20b4-11e8-9048-240fc308e890.png)

Three processes are still running in the background after the crash occurs.

**Comment by thecoder75** [comment]
This issue has been addressed in v1.92.20180305 release scheduled for later today.
