### ISSUE TITLE
Latest 1.92.20180305 release is crashing on startup

### ISSUE THREAD

**Issue by happykeppi** [thecoder75/liveme-pro-tools#16]
Re-release of 1.92.20180305 (updated one hour ago) is still crashing on startup, with different lines tough.

![2](https://user-images.githubusercontent.com/13066275/37001562-36385d44-20c7-11e8-8439-c7583b36af10.png)

**Comment by MaxCaulfield95** [comment]
Same problem here on Windows 10. I had to go back to the build from 3 days ago.

**Comment by thecoder75** [comment]
You need to delete the `Settings` file in App Settings directory to fix this issue as a corrupt entry in that file will cause this issue.
