### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by TuxNuX** [thecoder75/liveme-pro-tools#19]
Hi,
I use liveme-pro-tools-1.100.20180323 64bits linux and I have this error
but does not seem to hinder the work

![screenshot_20180324_173706](https://user-images.githubusercontent.com/17123357/37866402-aef11c4a-2f8a-11e8-9e01-e22249397389.png)

**Comment by thecoder75** [comment]
Are you running the latest version as this bug was briefly in a previous build but was addressed in a later build.  Also if the database files get corrupt, they can cause this error as well.

**Comment by TuxNuX** [comment]
I use the latest version :)
![screenshot_20180328_150106](https://user-images.githubusercontent.com/17123357/38030445-ec3da95e-3298-11e8-9d0f-5b6ab437a04e.png)
