### ISSUE TITLE
JDHttpAPI

### ISSUE THREAD

**Issue by prince911** [thecoder75/liveme-pro-tools#2]
https://imgur.com/a/DXPLN

JDownloader2 does not want to add JDHttpAPI

what should I do
extensions.installed.json

["chat","folderwatch","eventscripter","jdhttpapi","scheduler","infobar","translator"]

extensionInfos.json

[ {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.antistandby.AntiStandbyConfig",
  "quickToggle" : true,
  "headlessRunnable" : true,
  "description" : "Simply prevents your computer from going into standby or sleep mode to keep downloads active.",
  "lng" : "en_US",
  "iconPath" : "settings",
  "linuxRunnable" : false,
  "macRunnable" : true,
  "name" : "Bye-bye, Standby!",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.antistandby.AntiStandbyExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\AntiShutdown.jar"
}, {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.eventscripter.EventScripterConfig",
  "quickToggle" : true,
  "headlessRunnable" : true,
  "description" : "Listens to internal JDownloader event, and allows to execute relevant scripts (Javascript)",
  "lng" : "en_US",
  "iconPath" : "event",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "Event Scripter",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.eventscripter.EventScripterExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\EventScripter.jar"
}, {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.extraction.ExtractionConfig",
  "quickToggle" : false,
  "headlessRunnable" : true,
  "description" : "Extracts all usual types of archives (zip,rar,7zip,...)",
  "lng" : "en_US",
  "iconPath" : "extract",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "Archive Extractor",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.extraction.ExtractionExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\Extraction.jar"
}, {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.folderwatchV2.FolderWatchConfig",
  "quickToggle" : true,
  "headlessRunnable" : true,
  "description" : "Add Links to JDownloader just by putting Linklist files (*.crawljob) in a special folder on your harddisk.",
  "lng" : "en_US",
  "iconPath" : "folder_add",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "Folder Watch",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.folderwatchV2.FolderWatchExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\FolderWatch.jar"
}, {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.chat.ChatConfig",
  "quickToggle" : true,
  "headlessRunnable" : false,
  "description" : "Contact JDownloader Developers and Supporters",
  "lng" : "en_US",
  "iconPath" : "chat",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "Chat",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.chat.ChatExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\JDChat.jar"
}, {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.shutdown.ShutdownConfig",
  "quickToggle" : false,
  "headlessRunnable" : true,
  "description" : "Automatically shut down, suspend, hibernate your PC or close JDownloader when downloads are finished.",
  "lng" : "en_US",
  "iconPath" : "logout",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "JD Shutdown",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.shutdown.ShutdownExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\JDShutdown.jar"
}, {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.schedulerV2.SchedulerConfig",
  "quickToggle" : true,
  "headlessRunnable" : true,
  "description" : "Define time schedules to execute actions, start downloads,...",
  "lng" : "en_US",
  "iconPath" : "wait",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "Scheduler",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.schedulerV2.SchedulerExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\Scheduler.jar"
}, {
  "settings" : true,
  "configInterface" : "org.jdownloader.extensions.infobar.InfoBarConfig",
  "quickToggle" : false,
  "headlessRunnable" : false,
  "description" : "Small floating panel with information on Downloads in realtime, and Drag'N'Drop Zone where you can add links, URLs or DLC files.",
  "lng" : "en_US",
  "iconPath" : "info",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "Info Bar",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.infobar.InfoBarExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\infobar.jar"
}, {
  "settings" : false,
  "configInterface" : "org.jdownloader.extensions.translator.TranslatorConfig",
  "quickToggle" : false,
  "headlessRunnable" : false,
  "description" : "This Extension can be used to edit JDownloader translations. You need a developer account to use this extension",
  "lng" : "en_US",
  "iconPath" : "language",
  "linuxRunnable" : true,
  "macRunnable" : true,
  "name" : "Translator",
  "version" : -1,
  "windowsRunnable" : true,
  "classname" : "org.jdownloader.extensions.translator.TranslatorExtension",
  "jarPath" : "D:\\Download\\JDownloader 2\\extensions\\translator.jar"
} ]

Is the text true ??

**Comment by thecoder75** [comment]
I don't run it on Windows, I run Linux but from what I see above it looks correct.  Did you modify the second file to list the plugin per the [instructions](https://github.com/nemec/JDHttpAPI) to make it show up in jDownloader2?

**Comment by prince911** [comment]
what you mean JDHttpApi.jar ?? 

the location in jDownloader2  extensions

**Comment by thecoder75** [comment]
The instructions listed on that site state that there are two files you need to edit, not one.  Did you edit the second file per the instructions?

**Comment by prince911** [comment]
no how i can edit the JDHttpApi.jar

i edite  extensionInfos.json

and extensions.installed.json

ant edite missung

**Comment by thecoder75** [comment]
Double check the files you edited and copy the extension to the Extensions folder again, basically if re-doing the steps for installation does not address it you will then need to contact the author or jDownloader2 for further support on this.

**Comment by prince911** [comment]
JDHttpApi.jar cant edited
 
what file you talk ?? 
https://imgur.com/a/PpgGq

**Comment by prince911** [comment]
thx for answer me 

can you upload 2 file edited for me 

i downloaded and copy and past 

last hope 

thx again

**Comment by thecoder75** [comment]
Sorry, I don't run Windows so mine would not work for you.
