### ISSUE TITLE
Downloads Suggestion

### ISSUE THREAD

**Issue by vanimox** [thecoder75/liveme-pro-tools#21]
This is an amazing tool, thank you!

I just wanted to point out one feature that would be amazing if it could be added to the program. Under the settings pane in the downloads section you are able to set a Filename Template, would it be possible to also add the ability to set the date that the replay was taken as well in the Filename Template?

For example:

%%replaydate%%      Date of the Replay

Thanks!

**Comment by thecoder75** [comment]
I'll see about adding it to the next release to both this and [LAMD](https://github.com/thecoder75/lamd/).

**Comment by thecoder75** [comment]
It's done and added.  Committing the update now.

**Comment by vanimox** [comment]
Thats awesome! Thank you!
