### ISSUE TITLE
When main issue is fixed, allow to grab .m3u8.

### ISSUE THREAD

**Issue by greatsalmonrun** [thecoder75/liveme-pro-tools#24]
Instead of simply the live.me website, please allow us grab the m3u8 directly.

**Comment by ddpk** [comment]
The only two possible things I could think you mean by this is 1.) Pasting a video ID to receive the videos m3u8 link or 2.) even just entering a liveme m3u8 to play in the video player.

**Comment by thecoder75** [comment]
Originally the Pro Tools allowed you to copy the m3u8 playlist URL to the clipboard but was changed to a direct web link for support with jDownloader2 and other downloaders.
