### ISSUE TITLE
Does the application work

### ISSUE THREAD

**Issue by prince911** [thecoder75/liveme-pro-tools#26]
Does the application work

Open profile or Replay  do not work

https://imgur.com/a/Z42hzim

plz add 
The history of what I searched for

error

https://imgur.com/a/MyyWUjG

**Comment by thecoder75** [comment]
Did you see the notice about [LewdNinja](https://github.com/lewdninja/) creating his own updated version of the app and fixing the issues now that Live.me has changed things yet again breaking all of the old tools?

He has an updated version that requires a Live.me account to now be used [here](https://github.com/lewdninja/liveme-pro-tools/)
