### ISSUE TITLE
32-Bit Builds Status

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-pro-tools#28]
Sometime in the future we will be dropping support for 32-bit builds on Windows and Linux.

Currently using download results from previous builds, I'm seeing less than 5% of Windows users are 32-bit and less than 10% on Linux.  

Our future plan is to move over to .NET Core/MONO for a majority of the backend with the end goal to be completely moved off of Electron in the end.  By dropping support then for 32-bit builds, it will allow us to focus on using technologies available to make the LMPT tool better and faster.

Feel free to leave comments regarding your thoughts on this here.

**Comment by Xqqz** [comment]
There were less than 7 Downloads for Windows32 Bit  on the last 2 releases
and less than 4 downloads on 32 Bit Linux...

So, i agree... seems not a lot  of downloads for 32 Bits.

Maybe a 32 bit release once every 6 months... One in June, one in December, if there's  not many downloads,  drop it permanently.

**Comment by thecoder75** [comment]
By removing the 32-bit builds, it would speed up our build process greatly as well.

**Comment by thecoder75** [comment]
Classifying this issue closed now as the build process has been switched over to produce 64-bit only versions.
