### ISSUE TITLE
First Run Wizard not working

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-pro-tools#3]
As per earlier reported issues, the new version (1.30) now installs correctly and registers, all seems fine except the First Run Wizard says will ask some questions, then hit next and goes to wizard finished with no Bookmarks/history etc imported. I have already sent you screens of the issue.

Only event log which might coincide shows

The server {7966B4D8-4FDC-4126-A10B-39A3209AD251} did not register with DCOM within the required timeout.

The \roaming\LiveMe Pro Tools folder has just a Logs directory - nothing else
The \roaming\LiveMe-pro-tools folder seems to havve the jsons, but all look like []

The files for importing are located in the \roaming\LiveMe Tools folder.

Can I simply overwrite the new empty jsons with the previous ones ? What (if anything) do I need to do with the three subfolders \cache; \GPUCache; \databases ?

Are you able to fix this given this information ?

Thanks

**Comment by thegeezer9999** [comment]
W10 x64
v1.30

**Comment by thecoder75** [comment]
If you have backup copies from an older version of LiveMe Pro Tools you can just overwrite the new ones.

The `cache`, `GPUCache` and `databases` folders are more related to Electron then LiveMe Pro Tools and can be deleted/overwritten/skipped.

I am reviewing the wizard now to see why its not prompting/detecting LiveMe Tools being installed.

**Comment by thecoder75** [comment]
The issue has been located and address regarding the wizard not detecting other installations.  Please download the new release and try again.
