### ISSUE TITLE
Request: Interface 

### ISSUE THREAD

**Issue by Xqqz** [thecoder75/liveme-pro-tools#31]
In the current LMPT version 1.225.20181228

this is the interface ( image ) 

![bandicam 2018-12-28 04-50-32-201](https://user-images.githubusercontent.com/38635388/50511916-7e607e00-0a5d-11e9-94c2-c4e19782cf2e.jpg)

Is it possible to move the DOWNLOADED  indicator  ( blue 1 ) to next to the DOWNLOAD button ( 2 ) location ? 
and place an icon for  PLAY button in column  pointing to the Replay Title 1 instead   ?  https://cdn1.vectorstock.com/i/1000x1000/94/55/play-button-web-icon-vector-13659455.jpg

New, or Old users might not be aware on where to click to play  on the new interface.

Thanks for reading.

**Comment by thecoder75** [comment]
A new update has been pushed out recently that resolved this and has also helped streamlined the UI for the replay list.
