### ISSUE TITLE
Program won't run in a new environment

### ISSUE THREAD

**Issue by mustang-sally** [thecoder75/liveme-pro-tools#44]
If you move your current config folder somewhere else and run the program, you'll get this error (I'm using [v1.232.20190105](https://github.com/thecoder75/liveme-pro-tools/releases/tag/v1.232.20190105)):

![image](https://user-images.githubusercontent.com/46511875/50911349-d82a5600-1416-11e9-83ac-634385353f39.png)

I ran a `git bisect` and found out this issue was introduced in commit 7e24e70d:

```js
let isFreshInstall = appSettings.get('general.fresh_install') == false
```

If we're running the program for the first time, `appSettings.get()` will actually return `undefined`. And in Javascript, `(undefined == false)` equals to `false`, therefore the program will always assume we're **not** running for the first time.

Prior to this commit, it used to be like this:

```js
let isFreshInstall = appSettings.get('general.fresh_install') == null
```

And it actually works, because in Javascript, `(undefined == null)` equals to `true`. Haha!

I'll be sending a PR soon to fix this problem, and I'll will be also addressing two more issues (if you don't mind):

* In my understanding, the wizard should run **only once**, but I couldn't find the code that sets `general.fresh_install` to `false` after the wizard has finished running.
* The wizard window is created [**every time** the program runs](https://github.com/mustang-sally/liveme-pro-tools/blob/ed430a15a94e2cd116ee82995ccf8682c9d23118/src/electron/index.js#L105-L124), but it should only be created if `general.fresh_install` is set to `true`.

I also have a couple of unrelated suggestions and fixes that I'll be soon sending you through pull requests. But don't feel obligated to accept them, obviously.

Thank you

**Comment by thecoder75** [comment]
Thank you, I've approved your pull request after making a couple minor changes.  Look forward to seeing your other ones too.
