### ISSUE TITLE
Should we change the UI font?

### ISSUE THREAD

**Issue by mustang-sally** [thecoder75/liveme-pro-tools#47]
In my pull request #46, I've suggested to update the current font ([Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro)), making it look better on Linux. ([screenshots for comparison here](https://github.com/thecoder75/liveme-pro-tools/pull/46#issuecomment-452947491)). 

However, @thecoder75 suggested me to open this thread so we can discuss the possibility of switching the font to something else. I'm not an UI designer, so I'll leave the discussion mostly to people who have expertise on the subject.

I suppose a good place to start looking for nice and free UI fonts is here:

https://fonts.google.com/?category=Sans+Serif

**Comment by thecoder75** [comment]
The app can also use the system's standard sans-serif font which would relieve the need for a CSS font.
