### ISSUE TITLE
Several issues with the current version 1.234

### ISSUE THREAD

**Issue by happykeppi** [thecoder75/liveme-pro-tools#50]
First, thanks to all contributors for their continuing work on this project. Unfortunately, I'm experiencing several problems with the latest release. The actual login takes a while now (at least 30 seconds, maybe more) before the bookmark scanning even begins on startup. There's also a similar delay in regard to checking the login itself in the settings.

The biggest problem, however, is that scanning the bookmarks for new replays (I have deactivated scanning for new followers and followings by the way) freezes all the time. Sometimes it stops at 3xx, sometimes later and it takes several minutes to increase the numbers before the entire home screen finally turns black. Loading and rendering of the bookmarks seems to be slower as well. Once the entire bookmark list is available, I can't open neither the replays, nor the fans or following lists. In other words, I can't use the application at all right now. (Windows 8.1 Update 1, 64bit)

**Comment by Xqqz** [comment]
@happykeppi 
Login ?.. when i START LMPT... it loads immediately, about 4 seconds in,  Bookmark starts to scan 

I have 2898 Bookmarked user ( at time of this posting ) , and it does NOT freeze anytime during the scan.

i am on Windows 7 Ultimate 64-bit...

it renders 500 users from bookmark in first 15 seconds.
1200 in 60 seconds ( slowed a bit )
1800 in 120 seconds
2240 in 180 seconds
2600  in 4 minutes
4 mins and 55 seconds  for 2898 users - rendered

so it might be a setting on your computer.. maybe ?

restart your computer and load LMPT before  any other processors to see if there's a difference in performance.

i have had the "black screen" on the bookmark popup before, i was running too many applications was the culprit....  task manager had shown CPU Usage at about 90%

**Comment by happykeppi** [comment]
I tested it on another computer without any problems. Looks like the problem is caused by something else. I am closing the issue.
