### ISSUE TITLE
Customized view of users/profiles

### ISSUE THREAD

**Issue by happykeppi** [thecoder75/liveme-pro-tools#51]
With the latest releases, values like LPM, VPM, and SPM have been added to the replay listing due to some requests. While I personally can't see the direct benefit of these numbers and think the entire listing is less clear now, I was wondering if you could make showing these values an optional thing by adding some viewing options to the settings for example.

Since I am using an external downloader, it's rather a disadvantage that the URL entry (COPY URL / Web URL) moved to the replay menu and it requires a further click to get it now. Would it be an idea to leave it up to the user to decide which buttons are shown on the right side and create a setting for that as well?

**Comment by happykeppi** [comment]
Yes, I meant "COPY URL". Sorry for the confusion. I don't mind those values being added since they might be useful for some people, but I also would appreciate if you could permanently hide them if you actually don't need them. Should be doable, shouldn't it?!

**Comment by blakrovv** [comment]
I do find the new columns extremely useful, the way I browse through lists. But I also understand it must be quite frustrating for users who copy a lot of links.
How about adding checkboxes to the replays list and a few buttons for global actions to perform on checked boxes? would it be useful?

**Comment by thecoder75** [comment]
Please see #72 regarding the links feature request.
