### ISSUE TITLE
Upgrading to Electron 4.0.1

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-pro-tools#53]
Would like to look into upgrading to a more recent version of Electron from the old 1.x.x release series since they were last updated in August 2018 and new 4.0.1 release is dated 01-04-2019.

Need to verify if anything will be broken and what updating/changing of code will be needed.  Also, what all benefits will there be for doing the update.

@mustang-sally made a recommendation of updating to 1.8.8 but would rather do a more recent version if we can.

**Comment by thecoder75** [comment]
First initial testing showed a slightly better video player, which may fix issues people have reported.
Also had to remove a couple old Electron API commands that are no longer supported.  
Other than that, everything seems to be working smoothly so far.

**Comment by thecoder75** [comment]
Please see the [electron-latest-branch](https://github.com/thecoder75/liveme-pro-tools/tree/electron-latest-branch) for right now.  I'll be releasing a test version later.

**Comment by mustang-sally** [comment]
I really liked the choice of using the default OS font in the UI. Looks good IMO.

The new native video player is pretty and all, but I disliked the fact it doesn't have a volume slider and it has this stupid pause button shows up every time you hover the cursor over the video. These "issues" were [already addressed](https://chromium.googlesource.com/chromium/src.git/+/77b8b6feb5418be0461ec0fe25863d854d663b24) by the Chromium team, but unfortunately Electron 4.0.0 uses an older version of Chromium.
