### ISSUE TITLE
Bookmark issues with version 1.305.20190116

### ISSUE THREAD

**Issue by happykeppi** [thecoder75/liveme-pro-tools#59]
After updating to the most recent version 1.305.20190116 all my bookmarks were completely gone; the list was completely empty, although the app scanned and showed new replays and followings on startup. I restored a three days old backup and now I am experiencing the issue that the bookmarks are showing up, but if I am opening a profile, the bookmark star is untagged. Anyone else having the same issue?

**Comment by thecoder75** [comment]
The bookmark issue has already been addressed and fixed in the 1.306.20190116 release scheduled for build.
