### ISSUE TITLE
Errors while opening/configuring the program

### ISSUE THREAD

**Issue by gabriel666999** [thecoder75/liveme-pro-tools#62]
hello I just discovered your program, but I can't use the last version (1.311.20190126)

this error I get after I open the program

![startup error](https://user-images.githubusercontent.com/47072994/51796739-e500c500-21de-11e9-92c7-9411ab7c1b42.png)

if I press ok the program still works, but I get this second error (and most annoying one) when I try to type the password of my account

![focusing in password field](https://user-images.githubusercontent.com/47072994/51796746-18435400-21df-11e9-8bcb-ee158556960e.png)

but if I close this error window, another one pops up immediatly, and so on... so I'm unable to type in my password

thanks

**Comment by gabriel666999** [comment]
Well I don't have any antivirus and it's a fresh Windows 7 installation with only Firefox installed so far.

Anyway I found out that both errors are gone once I close the program and open it again

But I tried running as administrator (after deleting the "liveme-pro-tools" folder in AppData), and I got the same error

Perhaps you can reproduce it if you move your "liveme-pro-tools" folder elsewhere and open the program

Thanks

**Comment by gabriel666999** [comment]
Maybe this can help:

https://github.com/nathanbuchar/electron-settings/issues/111

**Comment by thecoder75** [comment]
This issue should be fixed in the next.
