### ISSUE TITLE
New filter suggestion: by number of days since last replay.

### ISSUE THREAD

**Issue by blakrovv** [thecoder75/liveme-pro-tools#69]
I've been having issues with my bookmarks not highlighting new replays since v1.308. I think one cool way around would be adding one new filter to the Bookmarks window; something like being able to filter out accounts that haven't had any new replays for 'n' days. IOW, a new control where I put a number of days, say 3, it would then filter out any account that hasn't had new replays for the last 72 hours. This feature would also make it easier to browse through a lot of updated accounts.

Thank you guys!

**Comment by thecoder75** [comment]
I like the idea so much that I've added it to [v1.320.20190203](https://github.com/thecoder75/liveme-pro-tools/releases/v1.320.20190203)
