### ISSUE TITLE
Sorting Users by Videos in Search and Search by Video Title?

### ISSUE THREAD

**Issue by JustALostCoder** [thecoder75/liveme-pro-tools#71]
Can you also add sorting users by videos in search and the option of search by video titles ?

**Comment by thecoder75** [comment]
Unfortunately there is no way to sort users by videos in search as the search is constantly loading as you scroll so sorting would not work there.

Also, LiveMe's APIs do not allow searching by video title that we are aware of.  If there is an undocumented function call we can use to do this, then it would be added real quick as its something a lot of people would want to use.

**Comment by JustALostCoder** [comment]
Thanks. do you think when we can restrict search to profiles with the videos only ?

**Comment by thecoder75** [comment]
No, many users look for accounts with no replays for various reasons.  I'll never impose any limits or filters on searching due to this and other aspects.
