### ISSUE TITLE
Multiple Links

### ISSUE THREAD

**Issue by Uorfh** [thecoder75/liveme-pro-tools#72]
Ideas for next versions:

Add a box/button to grab all the links at once;
Add boxes next to the links so we could select only the links we want and a button as "Copy links from the selection" or something like that.

Thanks for all the work into this tool.

**Comment by thecoder75** [comment]
Good idea, any particular format desired for the output list?  Are you wanting to feed this into another program for downloading or something?  Please provide some details so I and others can begin researching and adding it in a future release.

**Comment by Uorfh** [comment]
I don't know about the others users but personally, i just save everything properly with actual names into notepad and later on i throw everything on Jdownloader, or, i just use my browser with an extension called "open multiple urls" to check which ones worth to grab and download.

Actually i think you could do the same with a button or sub-menu feature to open all at once into the user browser?

Anyway. to me, the raw m3u8 output it's enough but it's up to you and how hard would be to implement everything, if would be possible.

Thanks again for this amazing tool!

**Comment by thecoder75** [comment]
I was kind of thinking that was what you were looking for and was using jDownloader.  I'll see about adding it in a future release here soon.

**Comment by Uorfh** [comment]
Thanks, waiting and excited to this new features!

**Comment by thecoder75** [comment]
The user menu icon by the account lock will now allow you to select an option to copy the text to the clipboard for pasting into jDownloader.

**Comment by Uorfh** [comment]
I tested here and works like charm, but... It doesn't come as actual source (M3U8/FLV) but the actual URL link of the website which, at least for me, it's not helpful.

Another thing is, would be possible to format them?
It's coming like... Link1,link2,link3 etc all in the same line, so can we get like this:
Link1
Link2
Link3

**Comment by Uorfh** [comment]
Coder, thanks for making this happen but i was using here and managed to get two things:

If the replay it's expired, i can't grab using the all links button, for example - 164016228
They're 3, if you try to grab all at once, it'll comes out just one, so you have to do manually the other two.

And for some reason i'm not getting notifications anymore about my bookmarked users when they got new replays.
