### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by JustALostCoder** [thecoder75/liveme-pro-tools#74]
I installed new version and downloading starts but once all chunks are downloaded, it says download error.

Also I used to download using IDM through online HLS M3U8 players but it also is giving error as below

CAnnot load M3U8: Unable to fetch HTTP resource over HTTPS.

It used to work fine until yesterday.

**Comment by thecoder75** [comment]
Double-check in settings to see if Transcode settings are set to None or something else.  If its set to something else, then you need FFMPEG installed on your computer.  

But from your description of saying it downloads the chunks then fails, this tells me you have Transcode settings set to **H264 Fast** but don't have FFMPEG installed which will cause downloads to fail.

Regarding the second part, that sounds more like an issue with IDM that you will need to contact them about as they are attempting to download or connect to LiveMe in an unsupported fashion.
