### ISSUE TITLE
Looking into new chat server for open discussions

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-pro-tools#78]
Just wanted to let everyone know that I'm pissed as I'm guessing someone turned in my servers and got me banned from Discord now.  

I'm looking into other chat services that won't be so restrictive and stuff so we can still chat about the future of the tools.

Please bear with me while I keep looking.  Feel free to leave your thoughts, suggestions and feedback here.

**Comment by Viewer01** [comment]
Hey there! Well...well...It's a really pity! that thing with discord :/ but you know...maybe was the best way to try another services...
I'll definitely recommend Telegram, it doesn't have that "room" ability, but works good, and well here you have some features I've found by using it a couple of years:

**Details maybe pros or cons:**

- Groups can have up to 200k members (dunno how many did you have on discord)
- All accounts needs SMS text verification for login. (of course y'all have the common "alternatives")
- Supports all the media files...I think this it's not relevant but yeah, supports basically all the common format files.
- Supports different kind of bots, for example "HammerMan" "Mybot" etc....
- They say all the message are encrypted even to telegram, so, they offer a reward that basically says: If anyone who claims that Telegram messages can be deciphered is welcome to prove it that claim in our competition and win $300,000.

Well isn't too much, but, I think it's a good tool.
I have some groups there, but my mistake is invited too many freak people who doesn't respect the rules...so I've get banned so many times for be the creator lol

Finally, I will try 2 tools totally new for me: "ChatSecure" and "Tox" I will tested it and talk you later about what seems to me.

Regards!
Viewer! O.o

**Comment by thegeezer9999** [comment]
Hey Coder - keep me updated please. You can DM through Disc0rd or I can get info fro GH

Thanks

**Comment by thecoder75** [comment]
@thegeezer9999 I will keep things updated here while I work on an alternate.  Can't get back on Discord since they banned my email/login and stuff.

**Comment by thecoder75** [comment]
> Hey there! Well...well...It's a really pity! that thing with discord :/ but you know...maybe was the best way to try another services...
> I'll definitely recommend Telegram, it doesn't have that "room" ability, but works good, and well here you have some features I've found by using it a couple of years:
> 
> **Details maybe pros or cons:**
> 
> * Groups can have up to 200k members (dunno how many did you have on discord)
> * All accounts needs SMS text verification for login. (of course y'all have the common "alternatives")
> * Supports all the media files...I think this it's not relevant but yeah, supports basically all the common format files.
> * Supports different kind of bots, for example "HammerMan" "Mybot" etc....
> * They say all the message are encrypted even to telegram, so, they offer a reward that basically says: If anyone who claims that Telegram messages can be deciphered is welcome to prove it that claim in our competition and win $300,000.
> 
> Well isn't too much, but, I think it's a good tool.
> I have some groups there, but my mistake is invited too many freak people who doesn't respect the rules...so I've get banned so many times for be the creator lol
> 
> Finally, I will try 2 tools totally new for me: "ChatSecure" and "Tox" I will tested it and talk you later about what seems to me.
> 
> Regards!
> Viewer! O.o

Telegram is used more for illegal trading and other means than anything and don't want to really be associated with it in regards to my tools.

**Comment by Viewer01** [comment]
Well that make sense, so, take a look to Slack, are used by a lot of companies, and actually it's really similar to discord.

**Comment by monstergarden** [comment]
I through Gitter into the boat

**Comment by thecoder75** [comment]
I did set Gitter up but didn't have a chance to really check it out yet.

[![Gitter](https://badges.gitter.im/thecoderstoolbox/community.svg)](https://gitter.im/thecoderstoolbox/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by thecoder75** [comment]
Okay, I've settled on using Gitter now.  Buttons and links have been provided on all of the README pages for each active project now.
