### ISSUE TITLE
login

### ISSUE THREAD

**Issue by jakob6579** [thecoder75/liveme-pro-tools#83]
I have been having a problem with authentication. Sorry for my ignorance. I have used yopmail and gmail. the error I am getting: 

TransformError: Error: Request failed with PW:********* and **********@gmail.com. Got: {"ret":4051,"msg":"need active","data":{"access_token":"2061f02c110550743bc8abb88a368109d8514e47","expires_in":"5184000","refresh_token":"2061f02c150e0da683bf650b0a3e97430ec22a7a","sid":"5aabfd658e86af12d3a0ce52615c6104001","captcha":""}}. 

Running a Mac . I can log in through a browser

**Comment by thecoder75** [comment]
LiveMe Pro Tools requires you to create and verify an Email login first on the mobile app (Not Google or Facebook Login) in order for authentication to work.

From the first part of error message, its saying the account being used is not set up as an Email login account.
