### ISSUE TITLE
Sometimes LMPT is unable to download or watch replays

### ISSUE THREAD

**Issue by mustang-sally** [thecoder75/liveme-pro-tools#84]
I noticed that LMPT is unable to choose the correct video source of some live streams (mostly gaming-related, but I've experienced it on "regular" ones as well). This is a very rare issue, but it does happen. 

To demonstrate this, search for this replay id: `15541312286104237385`.

Trying to watch it shows me this error on developer's console:

![lm-error](https://user-images.githubusercontent.com/46511875/55362723-3ebc8e80-54b1-11e9-811a-f3c68a96410a.png)

And downloading fails as well:

![dl-error](https://user-images.githubusercontent.com/46511875/55362767-5c89f380-54b1-11e9-85e3-e433436bee52.png)

I have a fix for this already and I'll be sending a PR soon. Let me know what you think.

**Comment by thecoder75** [comment]
Pull request has been merged with the main branch.  Thank you.
