### ISSUE TITLE
one small issue with video rotate for Mac

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#91]
One small issue with video rotate for Mac(idk if this is an issue with windows).
I hope this makes sense lol
Rotating video works fine until I decide use the mouse to manually skip ahead the video (example, move ahead 5,10,15, etc minutes). So I Play a video, skip head with mouse, then while video is still playing, I press either alt + left arrow or Right arrow to rotate, video rotates in the direction I choose correctly but the video skips ahead sometimes 1 minute, 4 minutes or even like 20 minutes. Seems like a minor bug. It only happens after I manually skip ahead with mouse then I try to rotate video. Sometimes it works fine, but most times it just skips ahead. Hope I described it correctly.

**Comment by mustang-sally** [comment]
I wasn't able to reproduce this on a macOS vm. But if you find a consistent way to reproduce this, please let me know.

**Comment by stingersplash** [comment]
It seems to happen alot while the video is playing. Pausing video first, then click alt + Arrow direction seems to do a better job, but it still does it. I think it has to do with the left and right arrows since they also function as a 1 sec fast forward/reverse (not holding down alt). Maybe using alt+ different key for rotation would work? or just making alt+ left/right arrows for rotation only? Thanks again

**Comment by mustang-sally** [comment]
I think I've got it. When you click on the seek bar, the focus is passed to the seek bar. That's why if you hit the left or right arrow keys, the video will seek. I'm not sure if plyr (the player we're using) let us configure that behavior, so I'll look into that later. As a workaround for now: After you seek using the mouse, just click on the video again so the focus is removed from the seek bar.

**Comment by stingersplash** [comment]
wow, your right, that seems to work. Do you think there is a way to fix that? If not this workaround will do. Thanks again for getting back so quick.

**Comment by mustang-sally** [comment]
I've added a fix for this on #92, please try it out if you can

**Comment by thecoder75** [comment]
This fix was included in release: https://github.com/thecoder75/liveme-pro-tools/releases/tag/v1.337.20190423

**Comment by mustang-sally** [comment]
Thanks for quickly merging it @thecoder75. However, this issue actually affects all platforms, so you can change the release description if you want. :+1:

**Comment by stingersplash** [comment]
Hi, I just tried out the new release, but unfortunately it doesn't seem to fix it. The workaround you mentioned "After you seek using the mouse, just click on the video again so the focus is removed from the seek bar" still works perfectly. It's ok if it can't be fixed since the workaround works, just a minor inconvenience. Thanks again for the quick response.

**Comment by Xqqz** [comment]
This ISSUE also exsits in Windows Version 1.337.20190423

Sometimes when watching a video, and you choose the ALT + <-(left arrow) or ALT + -> (right arrow) , the video that is playing rotates a full 360 degrees. 

Only way to get it back to normal, is to shut down LMPT and restart it.....

**Comment by mustang-sally** [comment]
@stingersplash 

The fix I made was (somehow) not included in the latest release. Probably something went wrong in the building process, idk. You can try with this build I made myself, if you're interested: https://0x0.st/zbQ7.zip

@Xqqz 
Like I said, the fix wasn't included in the last release. Here's a Windows build if you want to test it again: https://0x0.st/zbQh.zip

Regarding the second issue you're having: I use the rotation feature very often and haven't experienced nothing like that, yet. Also, closing the player window and opening it again is sufficient to reset it, no need to completely restart LMPT. Nonetheless, if you find a consistent way to reproduce the bug you're having, please open a new issue.

@thecoder75 
I'm not sure if it's possible, but could you please "re-release" [the latest version](https://github.com/thecoder75/liveme-pro-tools/releases/tag/v1.337.20190423), but this time with the fix? Thank you!

**Comment by thecoder75** [comment]
Updated: [1.337.20190428 build](https://github.com/thecoder75/liveme-pro-tools/releases/tag/v1.337.20190428)

**Comment by stingersplash** [comment]
Hi, I just downloaded the update and the fix works. 
A quick tip, when using mouse to manually seek video ahead or backwards, wait for the video to finish loading(catching up to the time of the video you are seeking to) and resume playing before you try to rotate video. If you don't, the video will skip ahead or back like before. Thanks again for the quick fix, and if I see any more bugs I'll let report them.
