### ISSUE TITLE
New Release 1.339.20160624 chat bar/comments question?

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#94]
In the new Release 1.339.20160624 the chat bar/comments is shown in the bottom right corner while watching a replay, is there any way to turn this feature off?
I don't see an option in settings, unless I'm missing something.
Thanks

**Comment by thecoder75** [comment]
Sorry, at this time there is no way to turn it off.  There will be an update later on that will allow enabling/disabling this feature.

**Comment by thecoder75** [comment]
This issue has been resolved in the 1.340.20190625 release.  You can use the C key to toggle chat on/off in the player window and it'll remember your last choice too.
