### ISSUE TITLE
Quesion about terminated account vs User's account has no replays available notice....

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#95]
So it use to say "Uhh oh! This users account has been terminated by the looks of things!"
but now it says "Uhh oh! This users account has no public replays available for viewing!" 
It seems hard to tell what account is terminated or hidden/private when I'm about to unsub from an account. 
Is there away to separate the account notice
"Uhh oh! This users account has no public replays available for viewing!"  (hidden/private)
from
"Uhh oh! This users account has been terminated by the looks of things!"  (terminated)
btw, this was from issue #93
Thanks.

**Comment by thecoder75** [comment]
Yeah, even if the account is terminated it still will be there but have no replays.  LiveMe doesn't make it easy to figure out which is which and that is why the app was updated as some were still active but just hiding their replays.  

Until it can be figured out 100% accurately, the message will remain this for now.
