### ISSUE TITLE
Cool, easier and convenient idea for favorites list 

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#98]
I don't know if I should post this here or on gitter(I prefer here)but I have posted some issues/ideas on here before and you replied pretty quickly =) so here goes...

I think I have a good idea for the favorites pop window. So I follow 2 types of accounts
Account type 1- Someones account that has videos/replays who I would like to watch/follow.
Account type 2- Someones account that has followed other users who might have videos/replays that I would like to watch and eventually follow(pretty sure everyone does this).

The problem is that when you follow 1,000 people, and you use Account type 2 to search for new people to follow, I have to scroll up or down in my fav's to find Account type 2 user depending on how many new people I followed. So what I do is I keep unfollowing then re follow Account type 2 user(clicking the yellow star on the right of the account in my favorites to unfollow, then clicking it again to re follow) so when I refresh my favorites, and I scroll down,  all of my Account type 2 users will end up at the bottom of the list together, so it is easier for me to find them, instead of scrolling back up to find it after I just followed a bunch of new accounts. I hope this makes sense lol.

Maybe we can add a second favorites list(or multiple) that we can separate the two.
Similar to youtube when I favorite a video, I can create a new fav list, name it whatever I want, then add video to that list. So on the top of the LMPT favorites popup window, you can add a button  where we can easily search which fav list we want to view(Fav 1, Fav 2, Fav 3, Fav 4 etc) making it alot more easier and convenient. 
*Important- Fav 1 (default list) has every account that you followed in it and is viewable to everyone(like we have currently) but fav 2, Fav 3, Fav 4 etc(side favorites) are just for you to organize things easier 

Also as a side note, when you switch back and forth between fav's, it doesn't keep refreshing each favorites unless you click the refresh button for that particular fav list you're viewing.
Example - when you first open Liveme Pro Tool, click favorites, a popup window opens and automatically loads up your updated favorites. Once its done loading we can switch back and forth between our fav list by click the button. If you want to refresh fav 2, just click the refresh button, and only fav 2 refreshes. I think it will save alot time in-case say Fav 1(default list) has 1000 accounts and Fav 2 has 20, so you don't have to wait for all of them to refresh. Basically manually refresh for each Fav List.
I'm sorry, I know this is alot to read lol and I hope this makes sense. I don' know how this would affect backing up favorites and eventually restoring favorites but if this can be implemented, I think i would be a great additon. 
Also the Bigo app looks very similar liveme, I don't know much about it but I thought I would let you know since someone mentioned it on gitter.
Thanks again for coming back and continuing support.

**Comment by thecoder75** [comment]
I totally understand what you're talking about in regards to better having 2 lists than one and why.  It is something I've been thinking about for quite awhile now, just haven't implemented yet.

I've looked at doing the Bigo app and have found a few things that work easily but no API documentation or references yet that I can rely on to start building the app.  Hopefully it will change soon when I can give it some more time.

Anyways... will try and see what I can do in a near future release.

**Comment by thecoder75** [comment]
Okay, I actually began working on this feature so expect to see something not in the next release, but the one after.

**Comment by stingersplash** [comment]
Thanks alot for the quick response.
I'm sorry, I forgot to mention 2 other thing you might want to check out. Idk if I should post this here or create another topic about this, so I will do both just incase (going forward I will create a new topic just to keep them separate). 
1- So when you click on a video to play, a green eyeball on the left of the video shows up only after you refresh the accounts page. Would it be possible to have the green eyeball popup immediately after you play a video instead of having to refresh the page? Lets say an account has 200 replays, and you loose track of which replay you just watched, you would need to refresh all 200 replays to find where you left off.
2- Viewed profiles auto clear:
The most is 3 days before they clear, is it possible to make an option to not clear profiles you viewed, so they always have that blue eyeball next to it? Maybe an unlimited option?
These are just some small quality of life fixes I can think of at the moment. 
Thanks again Coder.

**Comment by thecoder75** [comment]
A preliminary Follows system is in place in the code.  It is buggy right now as things are still being drafted.  In order to try and test, you will need to download the repo and run as its classified extremely alpha/beta on this right now.

I also plan on adding a live refresh option to the Bookmarks and Follows windows as things are added from other windows too.

**Comment by stingersplash** [comment]
Ok so I Just downloaded and tried the new release (Mac release) and it seems to work but I noticed that after I scan my favorites(first time), finish viewing the new replays, exit out of favorite window and then re-scan for new favorites, it repeats the same favorites again. A workaround I found is if I leave the fav window open(original fav window), then I click for a second fav window to open, it doesn't repeat. This has actually happened once in a while before in the 1.342.20190915 and earlier releases and this workaround I used fixes it. I have only tried it once so maybe its a small hiccup, but as far as I know the original major issue is fixed. Over the next few days I'll try it out to see if the bug repeats, but I just thought you should know.

A preliminary Follows system is in place in the code, and plan on adding a live refresh option to the Bookmarks and Follows windows:
Idk much about the repo or how to install/try but no worries. Whenever you get the time to implement and make sure the features work 100%. If I see anymore bugs I will let you know.
Thanks again Coder

**Comment by thecoder75** [comment]
Closing this as the feature is in the code now and will be available in the next release.
