### ISSUE TITLE
Some small Quality of Life fixes..

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#99]
Here are 2 small Quality of Life fixes that might be easy to implement.

1- So when you click on a video to play, a green eyeball on the left of the video shows up only after you refresh the accounts page. Would it be possible to have the green eyeball popup immediately after you play a video instead of having to refresh the page? Lets say an account has 200 replays, and you loose track of which replay you just watched, you would need to refresh all 200 replays to find where you left off.
2- Viewed profiles auto clear:
The most is 3 days before they clear, is it possible to make an option to not clear profiles you viewed, so they always have that blue eyeball next to it? Maybe an unlimited option?
These are just some small quality of life fixes I can think of at the moment. 
Thanks again Coder.

**Comment by thecoder75** [comment]
I could possibly add an event receiver that would allow setting/changing the eye icon when a replay is viewed.

As far as the second one, I did that originally but ran into a major bug where the watched history file would get corrupt after awhile which is why the limit was imposed.

**Comment by thecoder75** [comment]
I'm merging the first request into #98 as its being tied into/updated with that one now.
